.Dd Feb 26, 2018
.Dt NOSTT 1
.Os
.Sh NAME
.Nm nostt
.Nd command line NOS Teletekst reader
.Sh SYNOPSIS
.Nm
.Op Ar page
.Sh DESCRIPTION
Displays the requested NOS Teletekst page on the command line.
Pages are identified by a three-digit number optionally followed by a subpage,
for example 100 or 302-2.
All subpages are printed if not specified.
.Pp
If no
.Ar page
argument is given,
.Nm
runs interactively.
.Sh ENVIRONMENT
.Bl -tag -width LC_MONETARY
.It Ev CLICOLOR
When set to 0, color output is disabled.
.It Ev CLICOLOR_FORCE
When set to 1, color output is enabled even output is redirect to a pipe or
file.
.El
.Sh SEE ALSO
Project page:
.Lk https://github.com/sjmulder/nostt
.Pp
Official NOS Teletekst web client:
.Lk https://nos.nl/teletekst
.Sh AUTHORS
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl .
.Sh BUGS
Teletext's 6-cell (2x3) block characters are displayed as % characters
as they cannot be accurately reproduced in a terminal without special fonts.
(The NOS viewer and API uses a custom font with these characters in the
.Qq private use
0xF000 Unicode range.)
.Pp
Color ouptut is disabled by default in MinTTY on Windows.
This is because MinTTY redirects standard output.
Set
.Ev CLICOLOR_FORCE
to 1 to force color output.
