name: build
on: push

jobs:
  ubuntu:
    strategy:
      matrix:
        agent: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.agent }}
    env:
      CFLAGS: '-Werror'
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libcurl4-openssl-dev libjson-c-dev
    - run: make
    - run: make check

  macos:
    strategy:
      matrix:
        agent: [macos-12, macos-14]
    runs-on: ${{ matrix.agent }}
    env:
      CFLAGS: '-I/opt/homebrew/include -Werror'
      LDFLAGS: '-L/opt/homebrew/lib'
    steps:
    - uses: actions/checkout@v3
    - run: brew install json-c  # curl comes preinstalled
    - run: make
    - run: make check

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libcurl4-openssl-dev libjson-c-dev
    - run: cmake -B build
    - run: cmake --build build

  debian:
    strategy:
      matrix:
        cc:
        - gcc-11
        - gcc-12
        - clang-13
        - clang-14
        - clang-15
        - clang-16
        - tcc
        #- musl-gcc  # no suitable libcurl
    runs-on: debian12-agent
    env:
      CC: '${{ matrix.cc }}'
      CFLAGS: '-Werror'
    steps:
    - uses: actions/checkout@v3
    - run: make
    - run: make check
