on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libcurl4-openssl-dev libjson-c-dev
    - run: make
    - run: make check
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: brew install json-c  # curl comes preinstalled
    - run: make
    - run: make check
